services:
  - type: web
    name: cloudvault-server
    runtime: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DEFAULT_STORAGE_QUOTA
        value: 1073741824
      - key: CLIENT_URL
        sync: false
      - key: STORAGE_PROVIDER
        value: cloudinary
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
